import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/common/Login'
import { GET_USER } from './api/graphql/Queries';
import { Client } from '../lib/types';
import { useRouter } from "next/router";
import { useEffect } from 'react';
import { getUser } from './api/login';



interface ClientPageProps{
  client_email: string;
  client: Client;
}

const ClientPage: NextPage<ClientPageProps> = ({client}) => {
  const router = useRouter();
  useEffect( () => {
    if(!client || client.userType != 'Client'){
      router.push('/');
    }
  });

  return (

    <div className="static bg-blue-800 text-white">
      <Head>
        <title>BTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <div className="flex gap-x-4 items-center justify-center pt-48 pb-4">
        <img src="/logo.svg" className="h-28"/>
          <h1 className="text-9xl italic font-semibold tracking-wide">
            CLIENT GANG
          </h1>
          <h2>Hi {client?.firstName}</h2>
        </div>
        <div className="m-auto w-1/2 max-w-lg bg-yellow-500 p-8 rounded-md">
          
          {Login()}
        </div>
       
      </main>

      <footer >
        <div className="absolute bottom-0 w-full text-lg text-center">© Copyright 2021 Bitcoin Trading System, All Rights Reserved</div>
      </footer>
    </div>

  )
}
export default ClientPage

export async function getServerSideProps(context) {
  if(Object.keys(context.query).length == 0){
    return {
      props: {
        client: null
      },
    };
  }
  const user = await getUser(context.query.email);
  
  return {
    props: {
      client: user,
    },
  };
}
