import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="static">
      <Head>
        <title>BTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <img src="/logo.svg" className="h-20"/>
        <h1 className="text-5xl text-center">
          Login
        </h1>
      </main>

      <footer >
        <div className="absolute bottom-0 w-full text-center">© Copyright 2021 Bitcoin Trading System, All Rights Reserved</div>
      </footer>
    </div>
  )
}

export default Home
